[project]
name = "fal-bundles-shared"
version = "0.1.0"
description = "Shared utilities for fal-bundles"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.0.0",
]

[tool.uv]
package = false
